[package]
name = "feather-vanilla-assets"
version = "0.1.0"
authors = [ "caelunshun <caelunshun@gmail.com>" ]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
ureq = { version = "2", default-features = false, features = [ "tls" ] }
zip = "0.5"
log = "0.4"
